version: '3.9'

services:
  mysql-bootcamp:
    image: mysql:8.0
    container_name: container-mysql-bootcamp
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: passer123@
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD

  phpmyadmin-bootcamp:
    container_name: phpmyadmin-bootcamp
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8085:80
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql-bootcamp
      PMA_USER: user
      PMA_PASSWORD: passer123@
    depends_on:
      - mysql-bootcamp
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local